// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AppServer.proto
#ifndef GRPC_AppServer_2eproto__INCLUDED
#define GRPC_AppServer_2eproto__INCLUDED

#include "AppServer.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace clima_server {

class AppServer final {
 public:
  static constexpr char const* service_full_name() {
    return "clima_server.AppServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::clima_server::ServerInfoReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::clima_server::ServerInfoReply>> AsyncServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::clima_server::ServerInfoReply>>(AsyncServerInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::clima_server::ServerInfoReply>> PrepareAsyncServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::clima_server::ServerInfoReply>>(PrepareAsyncServerInfoRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::clima_server::ServerInfoReply>* AsyncServerInfoRaw(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::clima_server::ServerInfoReply>* PrepareAsyncServerInfoRaw(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::clima_server::ServerInfoReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::clima_server::ServerInfoReply>> AsyncServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::clima_server::ServerInfoReply>>(AsyncServerInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::clima_server::ServerInfoReply>> PrepareAsyncServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::clima_server::ServerInfoReply>>(PrepareAsyncServerInfoRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::clima_server::ServerInfoReply>* AsyncServerInfoRaw(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::clima_server::ServerInfoReply>* PrepareAsyncServerInfoRaw(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ServerInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ServerInfo(::grpc::ServerContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ServerInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerInfo(::grpc::ServerContext* /*context*/, const ::clima_server::ServerInfoRequest* /*request*/, ::clima_server::ServerInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestServerInfo(::grpc::ServerContext* context, ::clima_server::ServerInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::clima_server::ServerInfoReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ServerInfo<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ServerInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::clima_server::ServerInfoRequest, ::clima_server::ServerInfoReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response) { return this->ServerInfo(context, request, response); }));}
    void SetMessageAllocatorFor_ServerInfo(
        ::grpc::experimental::MessageAllocator< ::clima_server::ServerInfoRequest, ::clima_server::ServerInfoReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::clima_server::ServerInfoRequest, ::clima_server::ServerInfoReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerInfo(::grpc::ServerContext* /*context*/, const ::clima_server::ServerInfoRequest* /*request*/, ::clima_server::ServerInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ServerInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::clima_server::ServerInfoRequest* /*request*/, ::clima_server::ServerInfoReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ServerInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::clima_server::ServerInfoRequest* /*request*/, ::clima_server::ServerInfoReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_ServerInfo<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_ServerInfo<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ServerInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerInfo(::grpc::ServerContext* /*context*/, const ::clima_server::ServerInfoRequest* /*request*/, ::clima_server::ServerInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ServerInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerInfo(::grpc::ServerContext* /*context*/, const ::clima_server::ServerInfoRequest* /*request*/, ::clima_server::ServerInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestServerInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ServerInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ServerInfo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_ServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerInfo(::grpc::ServerContext* /*context*/, const ::clima_server::ServerInfoRequest* /*request*/, ::clima_server::ServerInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* ServerInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* ServerInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ServerInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ServerInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::clima_server::ServerInfoRequest, ::clima_server::ServerInfoReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::clima_server::ServerInfoRequest, ::clima_server::ServerInfoReply>* streamer) {
                       return this->StreamedServerInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ServerInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ServerInfo(::grpc::ServerContext* /*context*/, const ::clima_server::ServerInfoRequest* /*request*/, ::clima_server::ServerInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedServerInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::clima_server::ServerInfoRequest,::clima_server::ServerInfoReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ServerInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ServerInfo<Service > StreamedService;
};

}  // namespace clima_server


#endif  // GRPC_AppServer_2eproto__INCLUDED
