// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AppServer.proto

#include "AppServer.pb.h"
#include "AppServer.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace clima_server {

static const char* AppServer_method_names[] = {
  "/clima_server.AppServer/ServerInfo",
};

std::unique_ptr< AppServer::Stub> AppServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AppServer::Stub> stub(new AppServer::Stub(channel, options));
  return stub;
}

AppServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ServerInfo_(AppServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AppServer::Stub::ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::clima_server::ServerInfoReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::clima_server::ServerInfoRequest, ::clima_server::ServerInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ServerInfo_, context, request, response);
}

void AppServer::Stub::experimental_async::ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::clima_server::ServerInfoRequest, ::clima_server::ServerInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ServerInfo_, context, request, response, std::move(f));
}

void AppServer::Stub::experimental_async::ServerInfo(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ServerInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::clima_server::ServerInfoReply>* AppServer::Stub::PrepareAsyncServerInfoRaw(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::clima_server::ServerInfoReply, ::clima_server::ServerInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ServerInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::clima_server::ServerInfoReply>* AppServer::Stub::AsyncServerInfoRaw(::grpc::ClientContext* context, const ::clima_server::ServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncServerInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

AppServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AppServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AppServer::Service, ::clima_server::ServerInfoRequest, ::clima_server::ServerInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AppServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::clima_server::ServerInfoRequest* req,
             ::clima_server::ServerInfoReply* resp) {
               return service->ServerInfo(ctx, req, resp);
             }, this)));
}

AppServer::Service::~Service() {
}

::grpc::Status AppServer::Service::ServerInfo(::grpc::ServerContext* context, const ::clima_server::ServerInfoRequest* request, ::clima_server::ServerInfoReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace clima_server

